plugin-components.md
Fixed broke (404) link in https://wintercms.com/docs/plugin/components page under "Page list properties" section, link with name "page Twig filter".
=> Fix broken link to page filter docs

console-scaffolding.md
Refs wintercms/storm#37 & https://github.com/wintercms/winter/discussions/201
=> Document new scaffolding commands

ajax-javascript-api.md, database-model.md, database-relations.md, plugin-components.md, plugin-registration.md, services-mail.md
This pull request is to improve the usability of the documentation.
The problem is that browsers translate values in `strong` tags. Values in tags `code` are skipped by browsers during translation.
Now I see the page like this:
=> Replace bold with code

backend-controllers-ajax.md, backend-forms.md, backend-import-export.md, backend-lists.md, backend-relations.md, backend-reorder.md, backend-views-partials.md, cms-mediamanager.md, cms-pages.md, database-model.md, database-relations.md, markup-function-form.md, markup-tag-for.md, plugin-registration.md, services-image-resizing.md, services-mail.md
This is the final usability improvement pull request.
It seems that I looked through everything.
=> Improving usability

cms-mediamanager.md
config/filesystem.php is actually config/filesystems
=> Correct filename to config/filesystems.php

plugin-components.md
I was unclear what a `set` was after reading the docs, so hopefully this should help.
=> Clarify documentation on sets

backend-forms.md
Clarify documentation to use multiple values for `trigger`
=> Multiple values for `trigger`

snowboard-introduction.md
=> Add section to document how to manually include snowboard assets

backend-forms.md
Field types wrap on mobile if using 3 columns.
Use 2 columns by default, 3 columns for width >= 576px.
=> Fix backend forms field types wrapping on small screens

events-introduction.md
=> Wildcard listener do not support priority

console-asset-compilation.md
This PR fixes a small typo in the docs for assets compilation "tailwindcss" was spelled with an extra "d" which could cause users to copy the wrong command and trying to run it.
=> Fix small typo in npx tailwindcss command

services-parser.md
Replaces #48. Documents https://github.com/wintercms/storm/pull/40
=> Document Parser enhancements

themes-development.md
Related to https://github.com/wintercms/winter/pull/495
=> Add multiple flag to theme fileupload fields

events-introduction.md
- fix missing space after `function` in closures
- remove Event::firing() notes since the event name is now provided as the first argument
- add details about the `$params` argument
- add note about emitter trait not supporting wildcard listeners
=> Improve wildcard listeners docs

services-helpers.md
Refs: https://github.com/wintercms/storm/pull/61
=> Add SVG utility docs

database-traits.md
Related: https://github.com/wintercms/storm/pull/94
=> Document HasSortableRelations trait

console-asset-compilation.md
This is another example for using the laravel mix system. As we already have a nice example with Tailwind CSS, I think include an example for backend usage can be useful. I made the example with Vue 3, as I think that's a well known and popular framework.
=> Add an example of using Vue in the backend

plugin-registration.md
Changed the file extension from htm to php in the controllers folder structure example.
https://wintercms.com/docs/plugin/registration#complex-structure
=> Controllers file extension from htm to php

database-model.md
Global scopes documentation seem to referr to Laravel 9.x (Winter 1.2.x) only, for previous version that are based on Laravel 6.x classes and methods are different.
See issue wintercms/winter#747
=> Fix global scopes

backend-forms.md
titleFrom does not work with a repeater in group mode
=> Extend titleFrom documentation with group mode

backend-forms.md
This PR follows the implementation of the icon picker available at https://github.com/wintercms/winter/pull/725
@LukeTowers Let me know if I missed anything
=> Add icon picker form widget instructions

backend-widgets.md
- Added instructions for connecting widget assets.
- Changed the file extension of widget partials on block diagrams from `.htm` to `.php`.
Documentation page: https://wintercms.com/docs/backend/widgets
=> Added instructions for inject widget assets

database/model.md
Related: https://github.com/wintercms/storm/pull/46 (specifically: https://github.com/wintercms/storm/commit/b977610d361cc25f24b05062e40a83a6d53680a8)
Mention the new addRelation() methods in the model extension docs.
=> Document HasRelationships trait methods

plugin-extending.md, services-behaviors.md
Refs: https://github.com/wintercms/storm/pull/134
=> Scoped and local extension docs

backend-forms.md
Document https://github.com/wintercms/winter/pull/902
=> Revise partial field documentation
